### ISSUE TITLE
Certificate can't be found on your local computer

### ISSUE THREAD

**Issue by otymartin** [fastlane/setups#11]
@KrauseFx @vpolouchkine 

What do I do here?
I'm trying to distribute Beta
```swift
[18:50:31]: Successfully logged in
[18:50:33]: Certificate ******* can't be found on your local computer
[18:50:33]: To not be asked about this value, you can specify it using 'keychain_path'
Path to a custom keychain:
```

```swift
fastlane_version "1.95.0"
default_platform :ios

platform :ios do
  lane :beta do
    cert
    sigh
    gym
    crashlytics(
      api_token: "****",
      build_secret: "****",
      groups: "Beta-101",
      notes: "First Beta Release"
    )
  end
end
```

**Comment by vpolouchkine** [comment]
Looks like you're missing a private key. To fix this, you can revoke this certificate and regenerate using `cert`. As an alternative, you can use `match`.

**Comment by otymartin** [comment]
@vpolouchkine Hey, I'm totally new to this tool so would appreciate some more detailed instructions. How do I revote the certificate? Do i replace `cert` in my `FastFile` with `match`?

Thanks

**Comment by vpolouchkine** [comment]
No worries – as a first step, I recommend reading https://codesigning.guide/ and https://github.com/fastlane/fastlane/tree/master/match

If this is something that you think will work for you (eg. you're comfortable keeping everything in Git), you can replace calls to `cert` and `sigh` by `match`. You probably will need to flush your certificates first by calling `match nuke development` (see https://github.com/fastlane/fastlane/tree/master/match#nuke).

**Comment by otymartin** [comment]
Very detailed thanks - looking into this now! 👍

**Comment by otymartin** [comment]
@vpolouchkine I keep getting stuck here even in the `match` setup
```
[20:05:42]: To not be asked about this value, you can specify it using 'keychain_path'
Path to a custom keychain: ```
Where do I find this custom keychain path?

**Comment by vpolouchkine** [comment]
Did you run `match nuke development`?

**Comment by otymartin** [comment]
@vpolouchkine I did - both `match nuke development` and `match nuke distribution`

**Comment by vpolouchkine** [comment]
Well, you can get the keychain path by running `security list-keychains -d user`. Can you please post the full log?

**Comment by otymartin** [comment]
```swift
+-----------------------+-----------------------------------------------+
|                        Summary for match 0.6.1                        |
+-----------------------+-----------------------------------------------+
| verbose               | true                                          |
| git_url               | https: *************.git |
| type                  | development                                   |
| git_branch            | master                                        |
| app_identifier        | com. *************. *************                   |
| username              |  *************                       |
| keychain_name         | login.keychain                                |
| readonly              | false                                         |
| team_id               |  *************                                    |
| force                 | false                                         |
| shallow_clone         | false                                         |
| force_for_new_devices | false                                         |
| skip_docs             | false                                         |
+-----------------------+-----------------------------------------------+

INFO [2016-06-23 21:04:58.13]: Cloning remote git repo...
INFO [2016-06-23 21:04:58.13]: $ git clone ' ************* *************.git' '/var/folders/wm/lph1cd916md_ypy_3jfvb6jm0000gn/T/d20160623-69032-cugq7s'
INFO [2016-06-23 21:04:58.15]: ▸ Cloning into '/var/folders/wm/lph1cd916md_ypy_3jfvb6jm0000gn/T/d20160623-69032-cugq7s'...
INFO [2016-06-23 21:04:59.59]: ▸ remote: Counting objects: 7, done.
INFO [2016-06-23 21:04:59.59]: ▸ remote: Compressing objects: 100% (4/4), done.
INFO [2016-06-23 21:04:59.59]: ▸ remote: Total 7 (delta 0), reused 4 (delta 0), pack-reused 0
INFO [2016-06-23 21:04:59.60]: ▸ Unpacking objects: 100% (7/7), done.
INFO [2016-06-23 21:04:59.64]: ▸ Checking connectivity... done.
INFO [2016-06-23 21:04:59.65]: 🔓  Successfully decrypted certificates repo
INFO [2016-06-23 21:04:59.71]: Verifying that the certificate and profile are still valid on the Dev Portal...
WARN [2016-06-23 21:05:03.10]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now

+-------------+-------------------------+
|        Summary for cert 1.4.1         |
+-------------+-------------------------+
| development | true                    |
| force       | true                    |
| username    | otyeka.martin@gmail.com |
| team_id     | *************              |
+-------------+-------------------------+

INFO [2016-06-23 21:05:03.11]: Starting login with user ' *************@gmail.com'
INFO [2016-06-23 21:05:05.76]: Successfully logged in
INFO [2016-06-23 21:05:06.79]: 🔒  Successfully encrypted certificates repo

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not create another certificate, reached the maximum number of available certificates.

URL: https://api.github.com/search/issues?q=Could%20not%20create%20another%20certificate,%20reached%20the%20maximum%20number%20of%20available%20certificates.+repo:fastlane/fastlane
➡️  Error Certificate for "AppStore" on Sigh step
   https://github.com/fastlane/fastlane/issues/3900 [open] 27 💬
   4 weeks ago

➡️  Could not create another certificate, reached the maximum number of available certificates.
   https://github.com/fastlane/fastlane/issues/3472 [closed] 9 💬
   08 Mar 2016

➡️  Could not create another certificate, reached the maximum number of available certificates
   https://github.com/fastlane/fastlane/issues/3123 [closed] 10 💬
   08 Mar 2016

and 8 more at: https://github.com/fastlane/fastlane/search?q=Could not create another certificate, reached the maximum number of available certificates.&type=Issues&utf8=✓
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Could not create another certificate, reached the maximum number of available certificates. (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:140:in `rescue in create_certificate'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:136:in `create_certificate'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:37:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:6:in `launch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.1/lib/match/generator.rb:19:in `generate_certificate'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.1/lib/match/runner.rb:49:in `certificate'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.1/lib/match/runner.rb:17:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.1/lib/match/commands_generator.rb:55:in `block (3 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.1/lib/match/commands_generator.rb:121:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.1/lib/match/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.1/bin/match:6:in `<top (required)>'
	from /usr/local/bin/match:23:in `load'
	from /usr/local/bin/match:23:in `<main>'
```

**Comment by vpolouchkine** [comment]
Apologies for the late reply. Looks like you've maxed our the certificates slots. Running `match nuke development` should fix that.

**Comment by KrauseFx** [comment]
I'll close this issue, please submit an issue on the fastlane main repo instead 👍
